DROP TABLE DONANTE CASCADE CONSTRAINT;
DROP TABLE DONACION CASCADE CONSTRAINT;
DROP TABLE FORMULARIO CASCADE CONSTRAINT;
DROP TABLE REALIZA CASCADE CONSTRAINT;
DROP TABLE RELLENA CASCADE CONSTRAINT;

CREATE TABLE DONANTE (NUM_DONANTE NUMBER(4) CONSTRAINT DONANTE_PK PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO1 VARCHAR2(50) NOT NULL,
    APELLIDO2 VARCHAR2(59) NOT NULL,
    IDENTIFICACION VARCHAR2(50) UNIQUE,
    FECHA_NACIMIENTO DATE NOT NULL,
    PAIS_NACIMIENTO VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(200) NOT NULL,
    POBLACION VARCHAR2(50) NOT NULL,
    CODIGO_POSTAL NUMBER(10) NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    TELEFONO2 NUMBER(9),
    FOTO BLOB,
    CICLO VARCHAR2(200) NOT NULL,
    CORREO_ELECTRONICO VARCHAR2(50) CHECK (CORREO_ELECTRONICO LIKE '%@%.%' AND CORREO_ELECTRONICO NOT LIKE '@%' AND CORREO_ELECTRONICO NOT LIKE '%@%@%'),
    SEXO VARCHAR(1Char),
    GRUPO_SANGUINEO VARCHAR2(50)
);

CREATE TABLE DONACION (NUM_DONACION NUMBER(2) CONSTRAINT DONACION_PK PRIMARY KEY,
    COD_COLECTA NUMBER(2),
    TIPO_DONACION VARCHAR2(10) CHECK (TIPO_DONACION LIKE 'SANGRE' OR TIPO_DONACION LIKE 'AFERESIS') NOT NULL,
    PULSO NUMBER(3) NOT NULL,
    TA_SIST NUMBER(4) NOT NULL,
    TA_DIAST NUMBER(4) NOT NULL,
    Hb_CAP NUMBER(4) NOT NULL,
    Hb_VEN NUMBER(4) NOT NULL,
    VOLUMEN NUMBER(3) NOT NULL,
    FECHA DATE
);

CREATE TABLE FORMULARIO (CODIGO NUMBER(2) CONSTRAINT FORMULARIO_PK PRIMARY KEY,
    PREGUNTA_1 VARCHAR2(2) CHECK (PREGUNTA_1 LIKE 'SI' OR PREGUNTA_1 LIKE 'NO'),
    PREGUNTA_2 VARCHAR2(2) CHECK (PREGUNTA_2 LIKE 'SI' OR PREGUNTA_2 LIKE 'NO'),
    PREGUNTA_3 VARCHAR2(2) CHECK (PREGUNTA_3 LIKE 'SI' OR PREGUNTA_3 LIKE 'NO'),
    PREGUNTA_4 VARCHAR2(2) CHECK (PREGUNTA_4 LIKE 'SI' OR PREGUNTA_4 LIKE 'NO'),
    PREGUNTA_5 VARCHAR2(2) CHECK (PREGUNTA_5 LIKE 'SI' OR PREGUNTA_5 LIKE 'NO'),
    PREGUNTA_6 VARCHAR2(2) CHECK (PREGUNTA_6 LIKE 'SI' OR PREGUNTA_6 LIKE 'NO'),
    PREGUNTA_7 VARCHAR2(2) CHECK (PREGUNTA_7 LIKE 'SI' OR PREGUNTA_7 LIKE 'NO'),
    PREGUNTA_8 VARCHAR2(2) CHECK (PREGUNTA_8 LIKE 'SI' OR PREGUNTA_8 LIKE 'NO'),
    PREGUNTA_9 VARCHAR2(2) CHECK (PREGUNTA_9 LIKE 'SI' OR PREGUNTA_9 LIKE 'NO'),
    PREGUNTA_10 VARCHAR2(2) CHECK (PREGUNTA_10 LIKE 'SI' OR PREGUNTA_10 LIKE 'NO'),
    PREGUNTA_11 VARCHAR2(2) CHECK (PREGUNTA_11 LIKE 'SI' OR PREGUNTA_11 LIKE 'NO'),
    PREGUNTA_12 VARCHAR2(2) CHECK (PREGUNTA_12 LIKE 'SI' OR PREGUNTA_12 LIKE 'NO'),
    PREGUNTA_13 VARCHAR2(2) CHECK (PREGUNTA_13 LIKE 'SI' OR PREGUNTA_13 LIKE 'NO'),
    PREGUNTA_14 VARCHAR2(2) CHECK (PREGUNTA_14 LIKE 'SI' OR PREGUNTA_14 LIKE 'NO'),
    PREGUNTA_15 VARCHAR2(2) CHECK (PREGUNTA_15 LIKE 'SI' OR PREGUNTA_15 LIKE 'NO'),
    PREGUNTA_16 VARCHAR2(2) CHECK (PREGUNTA_16 LIKE 'SI' OR PREGUNTA_16 LIKE 'NO'),
    PREGUNTA_17 VARCHAR2(2) CHECK (PREGUNTA_17 LIKE 'SI' OR PREGUNTA_17 LIKE 'NO'),
    PREGUNTA_18 VARCHAR2(2) CHECK (PREGUNTA_18 LIKE 'SI' OR PREGUNTA_18 LIKE 'NO'),
    PREGUNTA_19 VARCHAR2(2) CHECK (PREGUNTA_19 LIKE 'SI' OR PREGUNTA_19 LIKE 'NO'),
    PREGUNTA_20 VARCHAR2(2) CHECK (PREGUNTA_20 LIKE 'SI' OR PREGUNTA_20 LIKE 'NO'),
    PREGUNTA_21 VARCHAR2(2) CHECK (PREGUNTA_21 LIKE 'SI' OR PREGUNTA_21 LIKE 'NO'),
    PREGUNTA_22 VARCHAR2(2) CHECK (PREGUNTA_22 LIKE 'SI' OR PREGUNTA_22 LIKE 'NO'),
    PREGUNTA_23 VARCHAR2(2) CHECK (PREGUNTA_23 LIKE 'SI' OR PREGUNTA_23 LIKE 'NO'),
    PREGUNTA_24 VARCHAR2(2) CHECK (PREGUNTA_24 LIKE 'SI' OR PREGUNTA_24 LIKE 'NO'),
    PREGUNTA_25 VARCHAR2(2) CHECK (PREGUNTA_25 LIKE 'SI' OR PREGUNTA_25 LIKE 'NO'),
    PREGUNTA_26 VARCHAR2(2) CHECK (PREGUNTA_26 LIKE 'SI' OR PREGUNTA_26 LIKE 'NO'),
    PREGUNTA_27 VARCHAR2(2) CHECK (PREGUNTA_27 LIKE 'SI' OR PREGUNTA_27 LIKE 'NO'),
    PREGUNTA_28 VARCHAR2(2) CHECK (PREGUNTA_28 LIKE 'SI' OR PREGUNTA_28 LIKE 'NO'),
    PREGUNTA_29 VARCHAR2(2) CHECK (PREGUNTA_29 LIKE 'SI' OR PREGUNTA_29 LIKE 'NO'),
    PREGUNTA_30 VARCHAR2(2) CHECK (PREGUNTA_30 LIKE 'SI' OR PREGUNTA_30 LIKE 'NO'),
    PREGUNTA_31 VARCHAR2(2) CHECK (PREGUNTA_31 LIKE 'SI' OR PREGUNTA_31 LIKE 'NO'),
    PREGUNTA_32 VARCHAR2(2) CHECK (PREGUNTA_32 LIKE 'SI' OR PREGUNTA_32 LIKE 'NO'),
    PREGUNTA_EXCLUSION_1 VARCHAR2(2) CHECK (PREGUNTA_EXCLUSION_1 LIKE 'SI' OR PREGUNTA_EXCLUSION_1 LIKE 'NO'),
    PREGUNTA_EXCLUSION_2 VARCHAR2(2) CHECK (PREGUNTA_EXCLUSION_2 LIKE 'SI' OR PREGUNTA_EXCLUSION_2 LIKE 'NO'),
    PREGUNTA_EXCLUSION_3 VARCHAR2(2) CHECK (PREGUNTA_EXCLUSION_3 LIKE 'SI' OR PREGUNTA_EXCLUSION_3 LIKE 'NO'),
    APTO VARCHAR2(2) CHECK (APTO LIKE 'SI' OR APTO LIKE 'NO') NOT NULL,
    FECHA VARCHAR2(200),
    ESTADO_DONACION VARCHAR2(20) CHECK (ESTADO_DONACION LIKE 'APTO' OR ESTADO_DONACION LIKE 'EXCLUIDO' OR ESTADO_DONACION LIKE 'EXCLUIDO TEMPORAL'),
    FECHA_EXCLUSION VARCHAR2(200)
);

CREATE TABLE REALIZA (NUM_DONANTE NUMBER(2),
    NUM_DONACION NUMBER(2),
    CONSTRAINT REALIZA_PK PRIMARY KEY (NUM_DONANTE,NUM_DONACION),
    CONSTRAINT REALIZA_FK1 FOREIGN KEY (NUM_DONANTE) REFERENCES DONANTE(NUM_DONANTE) ON DELETE CASCADE,
    CONSTRAINT REALIZA_FK2 FOREIGN KEY (NUM_DONACION) REFERENCES DONACION(NUM_DONACION) ON DELETE CASCADE
);

CREATE TABLE RELLENA (NUM_DONANTE NUMBER(2),
    CODIGO NUMBER(2),
    CONSTRAINT RELLENA_PK PRIMARY KEY (NUM_DONANTE,CODIGO),
    CONSTRAINT RELLENA_FK1 FOREIGN KEY (NUM_DONANTE) REFERENCES DONANTE(NUM_DONANTE) ON DELETE CASCADE,
    CONSTRAINT RELLENA_FK2 FOREIGN KEY (CODIGO) REFERENCES FORMULARIO(CODIGO) ON DELETE CASCADE
);
    
    